# Generated by Django 5.0.7 on 2024-09-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_course_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='img',
            new_name='image',
        ),
    ]
