# Generated by Django 5.1 on 2024-09-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('login', models.DateTimeField()),
                ('logout', models.DateTimeField()),
                ('duration', models.DateTimeField()),
            ],
        ),
    ]
