# Generated by Django 5.1 on 2024-09-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_truck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truck',
            new_name='Track',
        ),
    ]
