# Generated by Django 5.1 on 2024-09-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
